stages:
  - test


check_version_numbers_and_doc_build:
  stage: test
  only:
      - master
      - develop
  script:
    - docker_image_build=ethcscs/sarus-ci-build:1.0.2
    - docker_image_run=ethcscs/sarus-ci-run:1.0.2-a

    - ./CI/check_that_version_file_is_up_to_date.sh
    - docker run --tty --rm -v $(pwd):/sarus-source ${docker_image_build} /sarus-source/CI/check_version_from_cmake.sh
    - docker run --tty --rm -v $(pwd):/sarus-source ${docker_image_run} /sarus-source/CI/run_documentation_build_test.sh

standalone_archive_debug:
  stage: test
  script:
    - . ./CI/utility_functions.bash
    - docker_image_build=ethcscs/sarus-ci-build:1.0.2
    - docker_image_run=ethcscs/sarus-ci-run:1.0.2-a

    # Build, install, test
    - build_type=Debug
    - build_install_test_sarus ${build_type} ${docker_image_build} ${docker_image_run}

  artifacts:
    name: "sarus-Debug-$CI_COMMIT_REF_NAME"
    paths:
      - sarus-Debug.tar.gz
      - README.md


standalone_archive_release:
  stage: test
  script:
    - . ./CI/utility_functions.bash
    - docker_image_build=ethcscs/sarus-ci-build:1.0.2
    - docker_image_run=ethcscs/sarus-ci-run:1.0.2-a

    # Build, install, test
    - build_type=Release
    - build_install_test_sarus ${build_type} ${docker_image_build} ${docker_image_run}

  artifacts:
    name: "sarus-Release-$CI_COMMIT_REF_NAME"
    paths:
      - sarus-Release.tar.gz
      - README.md


from_source_ubuntu18.04:
  stage: test
  only:
      - master
  script:
      - docker_image=ubuntu:18.04
      - docker run --tty --rm --privileged --user root -v $(pwd):/sarus-source ${docker_image} /sarus-source/CI/installation/test_driver.sh ${docker_image}

from_source_debian10:
  stage: test
  only:
      - master
  script:
      - docker_image=debian:10
      - docker run --tty --rm --privileged --user root -v $(pwd):/sarus-source ${docker_image} /sarus-source/CI/installation/test_driver.sh ${docker_image}

from_source_centos7:
  stage: test
  only:
      - master
  script:
      - docker_image=centos:7
      - docker run --tty --rm --privileged --user root -v $(pwd):/sarus-source ${docker_image} /sarus-source/CI/installation/test_driver.sh ${docker_image}

spack_package:
  stage: test
  only:
      - master
  script:
      - docker_image=ethcscs/sarus-spack:1.0.0-ubuntu16.04
      - docker run --tty --rm --privileged --user root -v $(pwd):/sarus-source ${docker_image} /sarus-source/CI/run_spack_package_test.sh
